// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtwygujpygvieszcikdp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0d3lndWpweWd2aWVzemNpa2RwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNjI3MjgsImV4cCI6MjA2MzYzODcyOH0.AWJpV85wBpRS8XZsB7viW27Mqin3iUhW4pUuj_9xVeg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);